// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftsLogger.API.Data;


#nullable disable

namespace ShiftsLogger.Migrations
{
    [DbContext(typeof(ShiftsDbContext))]
    partial class ShiftsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftsLogger.Models.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("ShiftId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            ShiftId = 1,
                            Duration = 8.0,
                            EndTime = new DateTime(2023, 10, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftName = "1st",
                            StartTime = new DateTime(2023, 10, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            ShiftId = 2,
                            Duration = 8.0,
                            EndTime = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftName = "2nd",
                            StartTime = new DateTime(2023, 10, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1
                        },
                        new
                        {
                            ShiftId = 3,
                            Duration = 8.0,
                            EndTime = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftName = "2nd",
                            StartTime = new DateTime(2023, 10, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 2
                        },
                        new
                        {
                            ShiftId = 4,
                            Duration = 8.0,
                            EndTime = new DateTime(2023, 10, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftName = "3rd",
                            StartTime = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 2
                        },
                        new
                        {
                            ShiftId = 5,
                            Duration = 8.0,
                            EndTime = new DateTime(2023, 10, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftName = "3rd",
                            StartTime = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 3
                        },
                        new
                        {
                            ShiftId = 6,
                            Duration = 8.0,
                            EndTime = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftName = "2nd",
                            StartTime = new DateTime(2023, 10, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 3
                        },
                        new
                        {
                            ShiftId = 7,
                            Duration = 8.0,
                            EndTime = new DateTime(2023, 10, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftName = "1st",
                            StartTime = new DateTime(2023, 10, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        },
                        new
                        {
                            ShiftId = 8,
                            Duration = 8.0,
                            EndTime = new DateTime(2023, 10, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftName = "1st",
                            StartTime = new DateTime(2023, 10, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 4
                        });
                });

            modelBuilder.Entity("ShiftsLogger.Models.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkerId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkerId");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            WorkerId = 1,
                            FirstName = "Tom",
                            LastName = "Foolery",
                            Title = "Laborer"
                        },
                        new
                        {
                            WorkerId = 2,
                            FirstName = "Sue",
                            LastName = "Smith",
                            Title = "Laborer"
                        },
                        new
                        {
                            WorkerId = 3,
                            FirstName = "Doug",
                            LastName = "Mitchell",
                            Title = "Foreman"
                        },
                        new
                        {
                            WorkerId = 4,
                            FirstName = "Mike",
                            LastName = "Wilson",
                            Title = "Apprentice"
                        });
                });

            modelBuilder.Entity("ShiftsLogger.Models.Shift", b =>
                {
                    b.HasOne("ShiftsLogger.Models.Worker", "Worker")
                        .WithMany("Shifts")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ShiftsLogger.Models.Worker", b =>
                {
                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
